# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget TritonCommon::triton-common-async-work-queue TritonCommon::triton-common-error TritonCommon::triton-common-sync-queue TritonCommon::triton-common-json TritonCommon::triton-common-table-printer TritonCommon::common-compile-settings TritonCommon::proto-library TritonCommon::grpc-service-library)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target TritonCommon::triton-common-async-work-queue
add_library(TritonCommon::triton-common-async-work-queue STATIC IMPORTED)

set_target_properties(TritonCommon::triton-common-async-work-queue PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:TritonCommon::common-compile-settings>"
)

# Create imported target TritonCommon::triton-common-error
add_library(TritonCommon::triton-common-error STATIC IMPORTED)

set_target_properties(TritonCommon::triton-common-error PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:TritonCommon::common-compile-settings>"
)

# Create imported target TritonCommon::triton-common-sync-queue
add_library(TritonCommon::triton-common-sync-queue INTERFACE IMPORTED)

set_target_properties(TritonCommon::triton-common-sync-queue PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target TritonCommon::triton-common-json
add_library(TritonCommon::triton-common-json INTERFACE IMPORTED)

set_target_properties(TritonCommon::triton-common-json PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/usr/include"
)

# Create imported target TritonCommon::triton-common-table-printer
add_library(TritonCommon::triton-common-table-printer STATIC IMPORTED)

set_target_properties(TritonCommon::triton-common-table-printer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:TritonCommon::common-compile-settings>"
)

# Create imported target TritonCommon::common-compile-settings
add_library(TritonCommon::common-compile-settings INTERFACE IMPORTED)

set_target_properties(TritonCommon::common-compile-settings PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_COMPILE_OPTIONS "\$<\$<OR:\$<CXX_COMPILER_ID:Clang>,\$<CXX_COMPILER_ID:AppleClang>,\$<CXX_COMPILER_ID:GNU>>:;-Wall;-Wextra;-Wno-unused-parameter;-Wno-type-limits;-Werror>;\$<\$<CXX_COMPILER_ID:MSVC>:/Wall;/D_WIN32_WINNT=0x0A00;/EHsc>"
)

# Create imported target TritonCommon::proto-library
add_library(TritonCommon::proto-library INTERFACE IMPORTED)

# Create imported target TritonCommon::grpc-service-library
add_library(TritonCommon::grpc-service-library INTERFACE IMPORTED)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/TritonCommonTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
